### PR TITLE
#44 Create the `Nimblehq GitHub` example project

### PR DESCRIPTION
**Pull request by manh-t**
https://github.com/nimblehq/flutter_templates/issues/44

## What happened 👀

Officially, there is no example project to show how we arrange our codebase yet.

The example application should show the list of our organization's Github repositories, so the project name could be nimblehq_github.
The main purposes of this project are:
- How we work with riverpod.
- How we arrange the MVVM layers (currently a resource to refer to could be [varun-matchmaking-flutter](https://gitlab.com/cloud_arv/agritech/service-matching/varun-matchmaking-flutter)).
- How we use retrofit or dio to make the network request.

## Insight 📝

I have created the example app based on `flutter_templates` init script:
- The project name: nimblehq_github
- The app name: Nimblehq Github
- The package identifier:
  - Android: `co.nimblehq.example.nimblehq_github`
  - iOS: `co.nimblehq.example.nimblehq-github`

In order to pass the CI, I have config `analysis_options.yaml` to exclude `examples` directory out of flutter analyze.

### CODE REVIEW

**Comment by doannimble** [comment]
@manh-t So we bring everything from the `template` to `example`, and when modifying/adding sth in `template`, we have to do the same with `example` 🤔

**Comment by manh-t** [comment]
@doannimble yes, please read [this discussion](https://nimble-co.slack.com/archives/C01NKCFNE6R/p1645590664932779) for more details

**Comment by manh-t** [comment]
We will not perform any action to this PR until #58 is clear 🙇

**Review by sleepylee — COMMENTED** [review]
I forgot to commit my comments here long time ago.

**Pull request closed without merging**
